name: Change Discord Message

permissions:
  contents: write


on:
  push:
    branches:
      - main
    paths:
      - "markdowns/**"

jobs: 
    echo_send:
        runs-on: ubuntu-latest
        strategy:
              matrix:
                    node-version: ['20.x']
        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: install discord.js
              run: npm install discord.js
            - name: install glob
              run: npm install glob
            - name: install dotenv
              run: npm install dotenv
            - name: run index.js
              env:
                DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
              run: node index.js
            - name: Commit state
              run: |
                git config user.name "github-actions"
                git config user.email "github-actions@github.com"
                git add .state/data.json
                git diff --cached --quiet || git commit -m "update state"
                git push
